
org: serverless
app: spider
stage: dev
component: website
name: spider
inputs:
  region: ${output:${stage}:${app}:ocr-bucket.region}
  bucketName: spider
  protocol: http
  src:
    src: ./
    hook: npm run build
    dist: ./build
    envPath: ./
    index: index.html
    error: index.html
  env:
    # get api url after below api service deployed.
    apiUrl: http://18.217.187.128:3333/
