org: serverless
app: spider
stage: dev
component: website
name: spider

inputs:
  bucketName: spider
  protocol: https
  src:
    src: ./
    hook: npm run build
    dist: ./build
    envPath: ./
    index: index.html
    error: index.html
